version: 0.0
os: windows
files:
  - source: /home/runner/work/aws-codedeploy-sample-tomcat/aws-codedeploy-sample-tomcat/src/target/SampleMavenTomcatApp.war
    destination: C:/sample-tomcat/
   # C:/tmp/codedeploy-deployment-staging-area/
#   - source: /scripts/configure_http_port.xsl
#     destination: /tmp/codedeploy-deployment-staging-area/
# hooks:
#   ApplicationStop:
#     - location: scripts/stop_application
#       timeout: 300
#   BeforeInstall:
#     - location: scripts/install_dependencies
#       timeout: 300
#   ApplicationStart:
#     - location: scripts/write_codedeploy_config.sh
#     - location: scripts/start_application
#       timeout: 300
#   ValidateService:
#     - location: scripts/basic_health_check.sh
