version: 0.0
os: windows
files:
  - source: /target/SampleMavenTomcatApp.war
    destination: C:/apache-tomcat-8.5.69-windows-x64/apache-tomcat-8.5.69/webapps
   # C:/tmp/codedeploy-deployment-staging-area/
#   - source: /scripts/configure_http_port.xsl
#     destination: /tmp/codedeploy-deployment-staging-area/
hooks:
  BeforeInstall:
    - location: run.bat
      runas: Administrator
#       timeout: 300
#   BeforeInstall:
#     - location: scripts/install_dependencies
#       timeout: 300
  ApplicationStart:
    - location: tomcat.bat
      runas: Administrator
  ValidateService:
    - location: check.bat
      runas: Administrator
